CREATE TABLE SAMPLE.BLOG (
 ID NUMBER(10, 0) NOT NULL,
 NAME NVARCHAR2(50)
);

ALTER TABLE SAMPLE.BLOG ADD PRIMARY KEY (ID);

INSERT INTO SAMPLE.BLOG VALUES ('1', 'Test001');
INSERT INTO SAMPLE.BLOG VALUES ('2', 'Test002');
INSERT INTO SAMPLE.BLOG VALUES ('3', 'Test003');