CREATE USER SAMPLE2
  IDENTIFIED BY samplepw
  DEFAULT TABLESPACE users
  TEMPORARY TABLESPACE temp
/
 
GRANT DBA TO SAMPLE2;
GRANT UNLIMITED TABLESPACE TO SAMPLE2;


CREATE TABLE SAMPLE2.EMP (
 EMP_NO VARCHAR2(10) NOT NULL,
 EMP_NAME VARCHAR2(50)
);

INSERT INTO SAMPLE2.EMP VALUES ('1', 'Yamada');
INSERT INTO SAMPLE2.EMP VALUES ('2', 'Tanaka');
INSERT INTO SAMPLE2.EMP VALUES ('3', 'Sato');
