CREATE USER sample
  IDENTIFIED BY samplepw
  DEFAULT TABLESPACE users
  TEMPORARY TABLESPACE temp
/
 
GRANT DBA TO SAMPLE;
GRANT UNLIMITED TABLESPACE TO SAMPLE;


CREATE TABLE SAMPLE.EMP (
 EMP_NO VARCHAR2(10) NOT NULL,
 EMP_NAME VARCHAR2(50)
);

INSERT INTO SAMPLE.EMP VALUES ('1', 'Yamada');
INSERT INTO SAMPLE.EMP VALUES ('2', 'Tanaka');
INSERT INTO SAMPLE.EMP VALUES ('3', 'Sato');
